[SKIP CI] hardens the container upstart entry script

diff --git a/overlay/usr/bin/entrypoint b/overlay/usr/bin/entrypoint
--- a/overlay/usr/bin/entrypoint
+++ b/overlay/usr/bin/entrypoint
@@ -12,17 +12,45 @@ then
     printf "\nWait for database server on '%s:%s' ...\n" "$LIME_DB_HOST" "${LIME_DB_PORT:-3306}"
     /usr/local/bin/wait-for "${LIME_DB_HOST}":"${LIME_DB_PORT:-3306}"
 else
-    printf "\nRequired environment variable '\$LIME_DATABASE_HOST' not set. Exiting ..."
+    printf "\nRequired environment variable '\$LIME_DATABASE_HOST' not set. Exiting ...\n"
     exit 1
 fi
 
+# Automated install of limesurvey is quite fragile and so we have to avoid that the install command is ever executed more than once.
+# If so, it will avoid the container from being restarted but also from being updated.
+# Lime survey isn't offering any good mechanism to catch the failing as there are side effects that influence the thrown exception.
+# Plugins is a persisted volume that we use for creating our custom "installation done" flag
 printf "\nSetup lime survey\n"
-php /var/www/app/application/commands/console.php install "${LIME_ADMIN_USER}" "${LIME_ADMIN_PASSWORD}" "${LIME_ADMIN_USER}" "${LIME_ADMIN_EMAIL}"
+printf "\nCheck if install has been performed already\n"
+INSTALLER_FLAG=plugins/install.done
+if ! [ -f "$INSTALLER_FLAG" ]; then
+    printf "\nInstall lime survey\n"
+    php /var/www/app/application/commands/console.php install "${LIME_ADMIN_USER}" "${LIME_ADMIN_PASSWORD}" "${LIME_ADMIN_USER}" "${LIME_ADMIN_EMAIL}" true
+    touch $INSTALLER_FLAG
+    echo "$(php -r 'include("application/config/version.php"); echo $config["versionnumber"];')" > $INSTALLER_FLAG
+else
+    printf "\nInstall already performed at former container start\n"
+fi
 
-printf "\nSetup lime survey email config\n"
+# Database update shall only be performed if there is a new version installed to avoid updatedb to cause a php stacktrace...
+# updatedb breaks if email.php has been templated in a former container start
+printf "\nPerform database update check\n"
+VERSION_INSTALL=$(cat $INSTALLER_FLAG)
+VERSION_FOLDER="$(php -r 'include("application/config/version.php"); echo $config["versionnumber"];')"
+if [ "$VERSION_INSTALL" = "$VERSION_FOLDER" ]; then
+    printf "\nNo database update needed\n"
+else
+    printf "\nPerform database update and see if version offset needs database migration\n"
+    php /var/www/app/application/commands/console.php updatedb
+fi
+
+# updatedb will break if we execute the command with a templated email.php
+# Since we check the versionnumber from the former install against the latest folder version, we can keep
+# the templating in here without condition as updatedb is only executed when the version changed and then it's working as expected
+printf "\nSetup lime survey email config\n\n"
 /usr/local/bin/gomplate -V -o /var/www/app/application/config/email.php -f /etc/templates/email.php.tmpl
 
-printf "\nStarting survey ...\n"
+printf "\nStarting survey ...\n\n"
 
 php-fpm7 -F &
 exec nginx -g "daemon off;"
